# Generated by Django 5.2.7 on 2025-11-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amazon_clone", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Approved"),
        ),
    ]
